# Basic Site Settings
remote_theme: daattali/beautiful-jekyll
title: "Data Waters"
description: "Your Data, Our Expertise: Together We Innovate. We specialize in data pipeline optimization, advanced analytics, and fostering a data-driven culture. Discover tailored solutions that drive efficiency and maximize ROI for your business. Contact us today!"
url: "https://paguasmar.github.io"
author: "Pedro Águas Marques"
avatar: "/imgs/logo.jpeg"

# Navbar Links
navbar-links:
  Home: "/"
  Case Studies: "/case-studies"
  About: "/about"
  Services: "/#services"
  Contact Us: "/contact"
  Schedule a Call: "https://calendly.com/pm19/30min"

# Social Network Links - Too slow
#social-network-links:
#  email: "pedromar2010+interview@gmail.com"
#  github: paguasmar
#  linkedin: paguasmar

# Site appearance
navbar-col: "#EAEAEA"
navbar-text-col: "#404040"
navbar-border-col: "#DDDDDD"
page-col: "#FFFFFF"
text-col: "#404040"
link-col: "#008AFF"
hover-col: "#0085A1"

# SEO Related
google_site_verification: Bn0CnJFS5PimjF6atbrryLrEqz6QvN8uzAtw2I1RSWI
keywords: "Data Waters,Pedro Águas Marques,Data Consultancy,Data Pipeline Optimization,Advanced Analytics Solutions,Data Engineering Services,Machine Learning Integration,Cloud Data Solutions,ETL Process Automation,Data-Driven Culture Workshops,Business Intelligence Consulting,Custom Data Solutions"

plugins:
  - jekyll-relative-links
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-responsive-image
relative_links:
  enabled: true
  collections: true
include:
  - CONTRIBUTING.md
  - README.md
  - LICENSE.md
  - COPYING.md
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - ISSUE_TEMPLATE.md
  - PULL_REQUEST_TEMPLATE.md
